### ISSUE TITLE
Question about create_dataset.py file

### ISSUE THREAD

**Issue by YFLEEL** [declare-lab/BBFN#14]
1) Do the steps of downloading the CMU-Multimodal SDK need to operate the Usage step? Should I download the dataset by running the steps in Usage (as shown in the figure), or just implement Install in the SDK, and then run ```python main.py --dataset <dataset_name> --data_path <path_to_dataset>``` to complete the steps of downloading data?
<img width="862" alt="截屏2023-07-24 17 20 59" src="https://github.com/declare-lab/BBFN/assets/37772356/16b0d626-3afa-4028-b37a-ed0794745a50">
2) The second parameter path_to_embedding provided in the load_emb() runtime needs to call the file, how should the file be obtained?
3) How to obtain the embedding_and_mapping.pt file required in ```CACHE_PATH = DATA_PATH + '/embedding_and_mapping.pt'```?
Looking forward to your reply ！
1）下载CMU-Multimodal SDK的步骤需要将其中的Usage步骤进行操作吗？我是应该通过运行Usage中的步骤来下载数据集（如图），还是在SDK中只需实现Install，后续通过运行python main.py --dataset <dataset_name> --data_path <path_to_dataset>来完成下载数据的步骤呢？
2）load_emb()运行时中提供的第二个参数path_to_embedding需要调用文件，该文件应该如何获取？
3）CACHE_PATH = DATA_PATH + '/embedding_and_mapping.pt'中需要的embedding_and_mapping.pt文件又该如何获取？
非常期待您的回答！

**Comment by Clement25** [comment]
Sorry for late reply. `Embedding_and_mapping.pt` can be created by yourself through iterating over all the words in the dataset and map to corresponding glove embeddings.
