### ISSUE TITLE
Some questions about use UR-FUNNY datasets

### ISSUE THREAD

**Issue by xushang1995** [declare-lab/BBFN#5]
hello , may I have a question?
When I was running this code with the UR-FUNNY dataset, I found that the file 'word_list.pkl' was used during the loading of dataset. But I didn't see this file in the dataset I downloaded. So, Which file in the dataset is processed? look forward to your help in answering
![1647089837(1)](https://user-images.githubusercontent.com/51730475/158018830-23d80baf-9178-441a-98eb-e435bc240259.png)

**Comment by Clement25** [comment]
We are sorry that the original file used in our experiments is missing. You can reconstruct it by picking the word with the most similar embedding vectors to that in 'word_embedding_indexes_sdk.pkl' (cosine similarity).

**Comment by xushang1995** [comment]
OK，I will try it , thanks a lot

**Comment by hadikachmar3** [comment]
Hello, @xushang1995 , if you created this file, can you please share it?

Best,
Hadi.
