### ISSUE TITLE
A question about sample input length

### ISSUE THREAD

**Issue by Decem-Y** [declare-lab/BBFN#6]
Is it necessary to provide consistent input lengths for the three modes of the model? If they are not consistent, for example, if the text length is long, do video and voice clips need to be padding? Or is there a better way to handle.

**Comment by Clement25** [comment]
Hi, I think it is necessary if you have aligned the modality sequences beforehand (in this case they are of the same length)

**Comment by Decem-Y** [comment]
> 

Thank you for your reply
